//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demirbaş.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginPanel
    {
        public string KullanıcıKodu { get; set; }
        public string KullanıcıAdi { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
        public string PasswordCheck { get; set; }
        public System.Guid ID { get; set; }
    }
}
