//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demirbaş.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EquipmentsEntities : DbContext
    {
        public EquipmentsEntities()
            : base("name=EquipmentsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TB_Mobile> TB_Mobile { get; set; }
        public DbSet<TB_Monitors> TB_Monitors { get; set; }
        public DbSet<TB_Notebooks> TB_Notebooks { get; set; }
        public DbSet<TB_Others> TB_Others { get; set; }
        public DbSet<TB_Printers> TB_Printers { get; set; }
        public DbSet<TB_Servers> TB_Servers { get; set; }
        public DbSet<TB_Software> TB_Software { get; set; }
        public DbSet<TB_VINN> TB_VINN { get; set; }
        public DbSet<LoginPanel> LoginPanel { get; set; }
    }
}
