//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demirbaş.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Mobile
    {
        public string UserCode { get; set; }
        public string Demirbas { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Number { get; set; }
        public string SerialNumber { get; set; }
        public string IMEI { get; set; }
        public string MAC { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string InvoiceNumber { get; set; }
        public string OldUser { get; set; }
        public Nullable<System.DateTime> KayıtTarihi { get; set; }
        public int ID { get; set; }
        public string KayitDurumu { get; set; }
    }
}
