//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demirbaş.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Monitors
    {
        public string UserCode { get; set; }
        public string Demirbas { get; set; }
        public string Brand { get; set; }
        public string Users { get; set; }
        public string BrandFeatures { get; set; }
        public string Place { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string InvoiceNumber { get; set; }
        public string OldUser { get; set; }
        public Nullable<System.DateTime> KayıtTarihi { get; set; }
        public int ID { get; set; }
        public string KayitDurum { get; set; }
        public string SerialNumber { get; set; }
    }
}
