//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demirbaş.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Notebooks
    {
        public string UserCode { get; set; }
        public string Users { get; set; }
        public string Vendor { get; set; }
        public string SerialNum { get; set; }
        public string PcName { get; set; }
        public string WifiMac { get; set; }
        public string EthMac { get; set; }
        public string OperationSystem { get; set; }
        public string Specification { get; set; }
        public string WindowsCdKey { get; set; }
        public string SSD { get; set; }
        public string SSDSerial { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string InvoiceNumber { get; set; }
        public string OldUser { get; set; }
        public Nullable<System.DateTime> KayıtTarihi { get; set; }
        public int ID { get; set; }
        public string KayitDurum { get; set; }
    }
}
