//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demirbaş.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Others
    {
        public string UserCode { get; set; }
        public string Users { get; set; }
        public string Brand { get; set; }
        public string SerialNumber { get; set; }
        public string Features { get; set; }
        public string Location { get; set; }
        public string Specification { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string InvoiceNumber { get; set; }
        public string OldUser { get; set; }
        public Nullable<System.DateTime> KayıtTarihi { get; set; }
        public int ID { get; set; }
    }
}
