//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demirbaş.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Printers
    {
        public string UserCode { get; set; }
        public string Brand { get; set; }
        public string IP { get; set; }
        public string BasicFeatures { get; set; }
        public string NetworkName { get; set; }
        public string Location { get; set; }
        public string InventoryNumber { get; set; }
        public string InvoiceContract { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<System.DateTime> KayıtTarihi { get; set; }
        public int ID { get; set; }
        public string SerialNumber { get; set; }
    }
}
