//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demirbaş.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_VINN
    {
        public string UserCode { get; set; }
        public string Users { get; set; }
        public string Operator { get; set; }
        public string SerialNumber { get; set; }
        public string IMEI { get; set; }
        public string DeviceName { get; set; }
        public string SımCardNo { get; set; }
        public string PIN1 { get; set; }
        public string PIN2 { get; set; }
        public string PUK1 { get; set; }
        public string PUK2 { get; set; }
        public string Special { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string OldUser { get; set; }
        public Nullable<System.DateTime> KayıtTarihi { get; set; }
        public int ID { get; set; }
    }
}
